Dockerfile
nccl-test-distributed-128-las1-mpijob.yaml
nccl-test-distributed-64-gdrcopy-las1-mpijob.yaml
nccl-test-distributed-64-las1-mpijob.yaml
nccl-test-distributed-a40-64-las1-mpijob.yaml

Includes InfiniBand performance test suite built with support for GPUDirect. It might not be necessary in this image, we might want to leave it out to keep the Dockerfile cleaner. Not sure yet.

Add InfiniBand perf test with CUDA support

---

Dockerfile.ubuntu20
Dockerfile.ubuntu22

Fix for syntax in the line `ENV export UCX_VFS_ENABLE=no` added in commit 3e2155e. It was setting the variable `$export` to the value `"UCX_VFS_ENABLE=no"` rather than `$UCX_VFS_ENABLE` to `"no"`.
&ofcir; I only noticed this while looking through all environment variables via `export -p`. It wasn't causing issues for me. I cannot tell whether the line truly even still needs to be there, since it was doing nothing until now.
So in case it may help, here is a fix to what it was originally intended to do.

Fix invalid ENV definition when setting UCX_VFS_ENABLE=no

---

nccl-test-distributed-h100-64-las1-mpijob.yaml
nccl-test-distributed-h100-64-sharp-las1-mpijob.yaml

Switch to the other solution for the known NCCL problem on H100s: https://docs.nvidia.com/deeplearning/nccl/release-notes/rel_2-18-1.html#rel_2-18-1

fix: Stop disabling LL128 for the H100s

---

.github/workflows/ubuntu-20.yml
README.md
mpi-operator/nccl-test-distributed-h100-64-las1-mpijob.yaml
mpi-operator/nccl-test-distributed-h100-64-sharp-las1-mpijob.yaml
slurm/nccl-test-distributed-a100-64-enroot.slurm
slurm/nccl-test-distributed-a100-64.slurm
slurm/nccl-test-distributed-h100-64-enroot-sharp.slurm
slurm/nccl-test-distributed-h100-64-enroot.slurm
slurm/nccl-test-distributed-h100-64.slurm

This change updates the [NCCL version to v2.18.3](https://github.com/NVIDIA/nccl/releases/tag/v2.18.3-1) for all CUDA 12 builds, and adds a new build with [CUDA 12.2.0](https://hub.docker.com/r/nvidia/cuda/tags?name=12.2.0-devel-ubuntu20.04).
There is no cuDNN release officially supporting CUDA 12.2 yet, so this builds the CUDA 12.2 image off of `nvidia/cuda:12.2.0-devel-ubuntu20.04` rather than `nvidia/cuda:12.2.0-cudnn8-devel-ubuntu20.04` (which does not yet exist).

NCCL v2.18.3 & CUDA 12.2

---

.github/workflows/build.yml
.github/workflows/ubuntu-20.yml
Dockerfile.ubuntu20
README.md

This change updates all CUDA 12 build configurations to use HPC-X v2.16, and adds an extra build argument to the Dockerfile for controlling another part of the distribution name that has changed in the latest update (`MLNX_OFED_LINUX-5` → `mlnx_ofed`).

build: Update HPC-X to v2.16 for CUDA 12 builds

---

.github/workflows/ubuntu-20.yml
Dockerfile.ubuntu20
README.md

This change updates the [NCCL version to v2.18.5](https://github.com/NVIDIA/nccl/releases/tag/v2.18.5-1) for all CUDA 12 builds.  It also updates the CUDA 12.2.0 image to [CUDA 12.2.2 with cuDNN](https://hub.docker.com/r/nvidia/cuda/tags?name=12.2.2-cudnn8-devel-ubuntu20.04).
[NCCL version v2.18.6](https://github.com/NVIDIA/nccl/releases/tag/v2.18.6-1) is tagged on the NCCL GitHub repository but has no official release by NVIDIA as of this time, so this PR is only for v2.18.5.

build: Update to NCCL v2.18.5 & CUDA 12.2.2

---

.github/workflows/ubuntu-20.yml
Dockerfile.ubuntu20

Updates to CUDA 12.3 and NCCL 2.19. WIP.

build: Add disabled CUDA 12.3, add `--allow-downgrades`.

---

.github/workflows/ubuntu-22.yml
README.md

This change bumps the NCCL version for CUDA 12.0.1 builds with Ubuntu 22.04 down to v2.18.5-1, down from v2.19.3-1. Unlike for Ubuntu 20.04, libnccl2 v2.19.3-1 is not available pre-built from NVIDIA on Ubuntu 22.04.

ci: Downgrade `ubuntu22` + `cu120`'s `nccl-version` to `2.18.5-1`

---

.github/workflows/ubuntu-20.yml
.github/workflows/ubuntu-22.yml
Dockerfile.ubuntu20
Dockerfile.ubuntu22

This change updates the following components:
NCCL is updated to version 2.20.3-1 for supported CUDA & OS versions, which are:
- CUDA 12.2 & 12.3 with Ubuntu 20.04
- CUDA 12.3 only with Ubuntu 22.04
The CUDA 12.3 releases have been bumped to the 12.3.2 patch, and the CUDA 12.3 × Ubuntu 20.04 build has been enabled, since it had been commented out previously due to issues that should already be fixed.
The CUDA 12.3 releases now use the newest version of cuDNN: [cuDNN 9](https://docs.nvidia.com/deeplearning/cudnn/release-notes.html#cudnn-9-0-0). This is exclusively available for CUDA 12.3 and the only cuDNN version available for CUDA 12.3, with the `nvidia/cuda` base images.
As noted in the cuDNN 9 release notes:
> This is the first major version bump of cuDNN in almost 4 years. There are …

feat: Update NCCL, CUDA, cuDNN, and HPC-X

---

README.md

This change updates the image tags in the README with the changes made in #31, including version updates and a new CUDA 12.3 × Ubuntu 20.04 image.

docs: Update README with new image tags

---

Dockerfile.ubuntu20

The link to the prebuilt GDRCopy distribution we used in the Ubuntu 20.04 images finally died. This change copies the code from the Ubuntu 22.04 images to build GDRCopy from source instead.

fix: Build GDRCopy from source on Ubuntu 20.04 as well

---

.github/workflows/ubuntu-20.yml
.github/workflows/ubuntu-22.yml
README.md

This change updates the version of HPC-X in all CUDA 12 image builds to v2.19, up from v2.18.
> [!NOTE]
> The release notes and documentation for the v2.19 release of HPC-X are available on NVIDIA's site:
> [**NVIDIA HPC-X Software Toolkit Rev 2.19.0**](https://docs.nvidia.com/networking/display/hpcxv219)

feat: Update HPC-X to v2.19

---

.github/workflows/ubuntu-20.yml
.github/workflows/ubuntu-22.yml
Dockerfile.ubuntu22
README.md

This change adds a build for CUDA 12.6 on Ubuntu 22.04 and 20.04. It also updates HPC-X to version 2.20 on all CUDA 12.x builds, and updates NCCL to the latest version available for each build, up to 2.23.4-1.
It additionally removes older odd-numbered builds for CUDA 12.1 and CUDA 12.3, which no longer receive updated NCCL builds from NVIDIA, and removes unsupported image tags from the README. (If CUDA 12.3 is still desired, we can add it back.)
The supported image tags after this change would be 12.0, 12.2, 12.4, and 12.6 on Ubuntu 22.04 and 20.04, as well as 11.8 only on Ubuntu 20.04.
This additionally includes a change for cross-arch build pipeline compatibility while building OpenMPI.

feat: Add CUDA 12.6 builds, update HPC-X & NCCL

---

slurm/nccl-test-distributed-gb200-nvl72-enroot.slurm

Example output for a full nvl72 rack run:
```text
#
536870912     134217728     float     sum      -1   1806.7  297.16  586.06      0   1835.9  292.43  576.74      0
1073741824     268435456     float     sum      -1   3108.8  345.38  681.17      0   2924.7  367.13  724.06      0
2147483648     536870912     float     sum      -1   5589.1  384.22  757.78      0   5474.6  392.26  773.62      0
4294967296    1073741824     float     sum      -1    10094  425.49  839.16      0    10141  423.54  835.32      0
8589934592    2147483648     float     sum      -1    20299  423.16  834.57      0    20006  429.37  846.82      0
```
Example performance for a multi-rack NVL72 run:
```text
#
536870912     134217728     float     sum      -1   2156.8  248.92  493.94      0   2093.7  256.42  508.83 …
```

feat(slurm): Add a GB200 NVL72 example

---

.github/workflows/ubuntu-20.yml
.github/workflows/ubuntu-22.yml
Dockerfile.ubuntu20
Dockerfile.ubuntu22
README.md
slurm/nccl-test-distributed-gb200-nvl72-enroot.slurm

This change updates the CUDA 12.8 image to use CUDA 12.8.1, up from 12.8.0, and updates the following components across all built images:
| Ver | NCCL     | HPC-X  | cuDNN      |
|-----|----------|--------|------------|
| Old | 2.25.1-1 | 2.22.0 | 9.7.0.66-1 |
| New | 2.26.2-1 | 2.22.1 | 9.8.0.87-1 |

feat: Update to CUDA 12.8.1, NCCL 2.26.2, HPC-X 2.22.1, and cuDNN 9.8.0

---

slurm/nccl-test-distributed-gb200-nvl72-enroot.slurm

[NCCL_NET_GDR_C2C docs](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-net-gdr-c2c)
> The NCCL_NET_GDR_C2C variable enables GPU Direct RDMA when sending data via a NIC attached to a CPU (i.e. distance PHB) where the CPU is connected to the GPU via a C2C interconnect. This effectively overrides the NCCL_NET_GDR_LEVEL setting for this particular NIC.
Performance with this example running across 20 racks
```
#
536870912     134217728     float     sum      -1   7108.4   75.53  150.95      0   7145.8   75.13  150.16      0
1073741824     268435456     float     sum      -1   9805.7  109.50  218.85      0   9819.6  109.35  218.54      0
2147483648     536870912     float     sum      -1    14980  143.36  286.52      0    15087  142.34  284.49      0
4294967296 …
```

feat: Update the GB200 with latest env var recommendations

---

.github/workflows/ubuntu-20.yml
.github/workflows/ubuntu-22.yml
Dockerfile.ubuntu20
Dockerfile.ubuntu22
README.md

This change adds builds for CUDA 12.9 and updates NCCL to version 2.26.5-1, up from 2.26.2-1, and HPC-X to version 2.23, up from 2.22.1. Also included are updated versions of the edits from #46 that no longer conflict with the recent README changes.

feat: Update to CUDA 12.9.0 & NCCL 2.26.5-1

---

README.md

The README was outdated and was missing information about GB200 systems. This replaces the A100 information at the top of the README with GB200 information, adds a link to the GB200 testing script, and adds a table of contents to make the document easier to navigate.

docs: Update system descriptions in the README, add table of contents

---

slurm/nccl-test-distributed-a100-64-enroot.slurm
slurm/nccl-test-distributed-a100-64.slurm
slurm/nccl-test-distributed-gb200-nvl72-enroot.slurm
slurm/nccl-test-distributed-h100-64-enroot-sharp.slurm
slurm/nccl-test-distributed-h100-64-enroot.slurm
slurm/nccl-test-distributed-h100-64.slurm

real world world training and inference sizes is never near 512MiB, real world is between 16MiB to 256MiB for DDP/TP/FSDP/etc

feat: test acutal real world msg size

---

Dockerfile.ubuntu22

The steps to install the `libcudnn9-dev` package changed slightly, and require `libcudnn9-headers` to be installed with it. This PR adds that package to the list of installs.

build: Install `libcudnn9-headers` dependency for `libcudnn9-dev`

---

mpi-operator/nccl-test-distributed-a100-64-gdrcopy-mpijob.yaml
mpi-operator/nccl-test-distributed-a100-64-mpijob.yaml
mpi-operator/nccl-test-distributed-a100-64-noib-mpijob.yaml
mpi-operator/nccl-test-distributed-a100-64-sharp-mpijob.yaml
mpi-operator/nccl-test-distributed-gb200-nvl72-mpijob.yaml
mpi-operator/nccl-test-distributed-h100-64-mpijob.yaml
mpi-operator/nccl-test-distributed-h100-64-sharp-mpijob.yaml
slurm/nccl-test-distributed-a100-64-enroot.slurm
slurm/nccl-test-distributed-gb200-nvl72-enroot.slurm
slurm/nccl-test-distributed-h100-64-enroot-sharp.slurm
slurm/nccl-test-distributed-h100-64-enroot.slurm
slurm/nccl-test-distributed-h100-64.slurm

**GB200**
Re-enable NVLS. It was disabled previously due to issues with older NCCL versions.
Enforce GB200 best practices to fail clearly if GB200 is not correctly functioning, ie do not fall back to shared memory transport if NVLINK is down. Enforce CUMEM functionality for faster buffer registrations.
**All**
Explicitly disable UCX as it is not needed by NCCL and can lead torandom crashes
Explicitly request CPU and memory from Slurm
Remove SHARP flag from non-SHARP tests as it is disabled by default

Update environment variables and job settings to latest best practice
